[package]
name = "mathforge-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
governor = "0.10.4"
prost = "0.14.4"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
tonic-prost-build = "0.14.6"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net"] }
tokio-stream = { version = "0.1.19", features = ["net"] }
